# Generated by Django 4.0.5 on 2022-06-29 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_APP', '0011_alter_applicant_document_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_set',
            name='applicant_cv',
        ),
        migrations.RemoveField(
            model_name='skill_set',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='skill_set',
            name='applicant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
    ]
